import Header from '@/widgets/header/header'
import Footer from '@/widgets/footer/footer'
import Head from 'next/head'

import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body>
        <Head>
            <link rel="prefetch" href="https://imagedelivery.net/" />
        </Head>
        <main className={'main_flex_container'}>
            <Header/>
            {children}
            <Footer />
        </main>
        </body>
        </html>
    )
}
